-- MySQL Script generated by MySQL Workbench
-- Fri Apr  8 13:14:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventario` ;

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8mb4 ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`marcas` ;

CREATE TABLE IF NOT EXISTS `inventario`.`marcas` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`modelos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`modelos` ;

CREATE TABLE IF NOT EXISTS `inventario`.`modelos` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(100) NOT NULL,
    `descripcion` VARCHAR(500) NULL,
    `marca_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_modelos_marcas1_idx` (`marca_id` ASC) VISIBLE,
    CONSTRAINT `fk_modelos_marcas1`
        FOREIGN KEY (`marca_id`)
        REFERENCES `inventario`.`marcas` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`proveedores` ;

CREATE TABLE IF NOT EXISTS `inventario`.`proveedores` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(45) NOT NULL,
    `rut` VARCHAR(11) NOT NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`facturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`facturas` ;

CREATE TABLE IF NOT EXISTS `inventario`.`facturas` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `numero` INT NOT NULL,
    `valor_adquirido` INT NULL,
    `rev_acumulada` INT NULL,
    `rev_periodo` INT NULL,
    `dep_acumulada` INT NULL,
    `rev_dep_acumulada` INT NULL,
    `dep_periodo` INT NULL,
    `valor_activo` INT NULL,
    `remanente` INT NULL,
    `proveedor_id` INT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_facturas_proveedores1_idx` (`proveedor_id` ASC) VISIBLE,
    CONSTRAINT `fk_facturas_proveedores1`
        FOREIGN KEY (`proveedor_id`)
        REFERENCES `inventario`.`proveedores` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`estados` ;

CREATE TABLE IF NOT EXISTS `inventario`.`estados` (
    `id` INT NOT NULL,
    `estado` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`productos` ;

CREATE TABLE IF NOT EXISTS `inventario`.`productos` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(100) NOT NULL,
    `inventario` VARCHAR(45) NULL,
    `serie` VARCHAR(45) NULL,
    `fecha_compra` DATE NULL,
    `fecha_uso` DATE NULL,
    `fecha_baja` DATE NULL,
    `folio` VARCHAR(45) NULL,
    `motivo_compra` VARCHAR(500) NULL,
    `modelo_id` INT NULL,
    `factura_id` INT NULL,
    `estado_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_productos_modelos1_idx` (`modelo_id` ASC) VISIBLE,
    INDEX `fk_productos_facturas1_idx` (`factura_id` ASC) VISIBLE,
    INDEX `fk_productos_estados1_idx` (`estado_id` ASC) VISIBLE,
    CONSTRAINT `fk_productos_modelos1`
        FOREIGN KEY (`modelo_id`)
        REFERENCES `inventario`.`modelos` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `fk_productos_facturas1`
        FOREIGN KEY (`factura_id`)
        REFERENCES `inventario`.`facturas` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `fk_productos_estados1`
        FOREIGN KEY (`estado_id`)
        REFERENCES `inventario`.`estados` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `inventario`.`usuarios` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `usuario` VARCHAR(45) NOT NULL,
    `clave` VARCHAR(100) NULL,
    `nombre_completo` VARCHAR(200) NULL,
    `cargo` VARCHAR(100) NULL,
    `administrador` TINYINT(1) NOT NULL DEFAULT 0,
    `autenticacion` VARCHAR(25) NOT NULL DEFAULT 'ldap',
    `correo` VARCHAR(45) NULL,
    `telefono` VARCHAR(45) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`asignaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`asignaciones` ;

CREATE TABLE IF NOT EXISTS `inventario`.`asignaciones` (
    `producto_id` INT NOT NULL,
    `usuario_id` INT NOT NULL,
    `ubicacion` VARCHAR(200) NOT NULL,
    `fecha_inicio` DATE NOT NULL,
    `hora_inicio` TIME NULL,
    `fecha_fin` DATE NULL,
    `hora_fin` TIME NULL,
    `devuelto` TINYINT(1) NOT NULL DEFAULT 0,
    `observaciones` MEDIUMTEXT NULL,
    PRIMARY KEY (`producto_id`, `usuario_id`),
    INDEX `fk_productos_has_usuarios_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
    INDEX `fk_productos_has_usuarios_productos1_idx` (`producto_id` ASC) VISIBLE,
    CONSTRAINT `fk_productos_has_usuarios_productos1`
        FOREIGN KEY (`producto_id`)
        REFERENCES `inventario`.`productos` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT `fk_productos_has_usuarios_usuarios1`
        FOREIGN KEY (`usuario_id`)
        REFERENCES `inventario`.`usuarios` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
